### ISSUE TITLE
Black screen with shaders

### ISSUE THREAD

**Issue by Funado15** [FINDERFEED/SolarCraftRepository#16]
Hello! I was playing the mod with the Sildur's Vibrant Shader, and every time i looked to a rune, the screen, except the entities and the rune energy, turned black
![2022-02-12_14 32 40](https://user-images.githubusercontent.com/87283440/153713462-2cbd77f9-aa5e-4588-8904-349caaf356fe.png)

**Comment by FINDERFEED** [comment]
Idk what can cause this but maybe the problem is that this shaders are not compatible with vanilla shaders (i am using vanilla shaders to create a pretty effect around pylons). Everything works fine with BSL shaders(screen doesnt go black but my shaders just stop working but its not a big issue). Sadly its mostly because of optifine breaking everything in vanilla rendering and fixing what optifine did is impossible because it is a closed source project. I think i will just do an option in config to disable my shaders in next update. (i think it will be out soon because i need to publish a quick fix for recipe output bug)

**Comment by Funado15** [comment]
Thanks! I put the BSL shaders and it works
