### ISSUE TITLE
Crash when i approach to a solar rune

### ISSUE THREAD

**Issue by Funado15** [FINDERFEED/SolarCraftRepository#17]
Hello again! My minecraft crash everytime i approach to the same solar rune, and idk why. This is the crash file
[crash-2022-02-24_18.42.16-server.txt](https://github.com/FINDERFEED/SolarCraftRepository/files/8134714/crash-2022-02-24_18.42.16-server.txt)

**Comment by FINDERFEED** [comment]
"Solar rune"? Maybe you mean a pylon? Anyway, i dont think that this is an issue with my mod because crash report doesnt even reference my code (and any other mod's code as well which is very strange). I looked into the code that is referenced in crash report and i can say that this crash is happening because when minecraft generates a chunk its trying to get a random entity count to spawn but max entity "weight" is for some reason less than minimum entity "weight" which causes to random between values <= than zero which is not allowed. I dont add any mob spawns to biomes.

**Comment by Funado15** [comment]
Okey, thanks anyway and sorry for the bother
